"""Added composite constraint for jobs table (api_id, source). Changed timestamp in job and users, so they work correctly

Revision ID: 04040412019d
Revises: 24a5f6e3af86
Create Date: 2025-10-04 14:06:21.845104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04040412019d'
down_revision = '24a5f6e3af86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('jobs_api_id_key'), type_='unique')
        batch_op.create_unique_constraint('unique_job_per_source', ['api_id', 'source'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint('unique_job_per_source', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('jobs_api_id_key'), ['api_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
