"""Added 2 new columns to Documents table: original_filename and updated_at. Removed polymorphic at least for now cause I'm not sure I wanna use it.

Revision ID: 092855949216
Revises: 7c0a645f40ce
Create Date: 2025-11-21 14:10:11.399948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '092855949216'
down_revision = '7c0a645f40ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_filename', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('original_filename')

    # ### end Alembic commands ###
