"""Fixed typo in jobs table

Revision ID: 0d3fbe1587aa
Revises: 7dbafcc752ea
Create Date: 2025-10-17 21:05:32.767205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d3fbe1587aa'
down_revision = '7dbafcc752ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employment_type', sa.String(), nullable=True))
        batch_op.drop_column('employer_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employer_type', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('employment_type')

    # ### end Alembic commands ###
