"""Add profile_image to Profile model

Revision ID: 174097efdadd
Revises: a61b04c8cc16
Create Date: 2025-10-31 22:49:41.474584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '174097efdadd'
down_revision = 'a61b04c8cc16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
