"""Add notification preference fields to User

Revision ID: 46f096c70821
Revises: b081e1dee076
Create Date: 2025-12-01 00:16:32.983182

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '46f096c70821'
down_revision = 'b081e1dee076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_contents')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('general_notifications_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('general_notifications_frequency', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('job_alerts_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('job_alerts_frequency', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('last_general_notification_sent', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_job_alert_sent', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_job_alert_sent')
        batch_op.drop_column('last_general_notification_sent')
        batch_op.drop_column('job_alerts_frequency')
        batch_op.drop_column('job_alerts_enabled')
        batch_op.drop_column('general_notifications_frequency')
        batch_op.drop_column('general_notifications_enabled')

    op.create_table('document_contents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], name=op.f('document_contents_document_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('document_contents_pkey'))
    )
    # ### end Alembic commands ###
