"""create ResumeForm table

Revision ID: 4a263f9f1eef
Revises: 716cf62cc645
Create Date: 2025-11-26 22:46:22.190424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a263f9f1eef'
down_revision = '716cf62cc645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('personalInfo', sa.JSON(), nullable=True),
    sa.Column('socialInfo', sa.JSON(), nullable=True),
    sa.Column('miscInfo', sa.JSON(), nullable=True),
    sa.Column('jobHistory', sa.JSON(), nullable=True),
    sa.Column('edHistory', sa.JSON(), nullable=True),
    sa.Column('projInfo', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume_form')
    # ### end Alembic commands ###
