"""add skills_extracted and skills_by_category to jobs and deleted skills

Revision ID: 6d29e15a42b0
Revises: 7561c361e05c
Create Date: 2025-11-13 20:12:46.934726

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6d29e15a42b0'
down_revision = '7561c361e05c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skills_extracted', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('skills_by_category', sa.JSON(), nullable=True))
        batch_op.drop_column('skills')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skills', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_column('skills_by_category')
        batch_op.drop_column('skills_extracted')

    # ### end Alembic commands ###
