"""add notification fields

Revision ID: 716cf62cc645
Revises: 092855949216
Create Date: 2025-11-25 01:01:17.417820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '716cf62cc645'
down_revision = '092855949216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('digest_interval_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_digest_sent', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_job_match_sent', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_profile_reminder_sent', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_login_notification_sent', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_login_notification_sent')
        batch_op.drop_column('last_profile_reminder_sent')
        batch_op.drop_column('last_job_match_sent')
        batch_op.drop_column('last_digest_sent')
        batch_op.drop_column('digest_interval_minutes')

    # ### end Alembic commands ###
