"""Add expires_at column to Job model

Revision ID: 7c0a645f40ce
Revises: bc884eb0a0a4
Create Date: 2025-11-21 00:08:06.906433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c0a645f40ce'
down_revision = 'bc884eb0a0a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###
