"""add employment_type and company_num_employees to jobs

Revision ID: 7dbafcc752ea
Revises: e439817fcd9e
Create Date: 2025-10-17 20:24:38.564432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dbafcc752ea'
down_revision = 'e439817fcd9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employer_type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('employer_type')

    # ### end Alembic commands ###
