"""Convert Resume and CoverLetter to inherit from Document with plural table names

Revision ID: 9728809fd88e
Revises: 310d9268f422
Create Date: 2025-10-05 16:51:07.974817

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9728809fd88e'
down_revision = '310d9268f422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=120), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('cover_letters',
    sa.Column('cover_letter_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cover_letter_id'], ['documents.document_id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('cover_letter_id')
    )
    op.create_table('resumes',
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['documents.document_id'], ),
    sa.PrimaryKeyConstraint('resume_id')
    )
    op.drop_table('cover_letter')
    op.drop_table('resume')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume',
    sa.Column('resume_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], name=op.f('resume_user_email_fkey')),
    sa.PrimaryKeyConstraint('resume_id', name=op.f('resume_pkey'))
    )
    op.create_table('cover_letter',
    sa.Column('cover_letter_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('cover_letter_job_id_fkey')),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], name=op.f('cover_letter_user_email_fkey')),
    sa.PrimaryKeyConstraint('cover_letter_id', name=op.f('cover_letter_pkey'))
    )
    op.drop_table('resumes')
    op.drop_table('cover_letters')
    op.drop_table('documents')
    # ### end Alembic commands ###
