"""Added saved_filters column in user table

Revision ID: a61b04c8cc16
Revises: 0d3fbe1587aa
Create Date: 2025-10-23 16:46:31.635527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a61b04c8cc16'
down_revision = '0d3fbe1587aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.profile_id'], ),
    sa.PrimaryKeyConstraint('profile_id', 'skill_name')
    )
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('skills')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saved_filters', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('saved_filters')

    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skills', sa.TEXT(), autoincrement=False, nullable=True))

    op.drop_table('skills')
    # ### end Alembic commands ###
