"""empty message

Revision ID: ae518dd54072
Revises: 6d29e15a42b0
Create Date: 2025-11-14 12:45:31.107488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae518dd54072'
down_revision = '6d29e15a42b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skills_extracted', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('skills_by_category', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('skills_by_category')
        batch_op.drop_column('skills_extracted')

    # ### end Alembic commands ###
