"""add matched_skills to recommended_jobs

Revision ID: b809c213e610
Revises: b7efc3b64bd8
Create Date: 2025-11-19 19:20:07.404001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b809c213e610'
down_revision = 'b7efc3b64bd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommended_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matched_skills', sa.ARRAY(sa.String()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommended_jobs', schema=None) as batch_op:
        batch_op.drop_column('matched_skills')

    # ### end Alembic commands ###
