"""Add notification fields to User model

Revision ID: bc884eb0a0a4
Revises: b809c213e610
Create Date: 2025-11-20 22:59:19.319491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc884eb0a0a4'
down_revision = 'b809c213e610'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommended_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('matched_skills', sa.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_id', name='unique_recommendation_per_user_job')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('login_streak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_streak_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('resume_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('resume_updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('skills', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('profile_completion', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('daily_digest_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('weekly_digest_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('followed_companies', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('followed_companies')
        batch_op.drop_column('weekly_digest_enabled')
        batch_op.drop_column('daily_digest_enabled')
        batch_op.drop_column('profile_completion')
        batch_op.drop_column('skills')
        batch_op.drop_column('resume_updated_at')
        batch_op.drop_column('resume_score')
        batch_op.drop_column('last_streak_date')
        batch_op.drop_column('login_streak')
        batch_op.drop_column('last_login')

    op.drop_table('recommended_jobs')
    # ### end Alembic commands ###
